### ISSUE TITLE
every second: Possible Tor bug, or possible attack if very frequent: Got 1 dropped cell on circ 17 (in state CONFLUX_LINKED None; old state CONFLUX_UNLINKED None)

### ISSUE THREAD

**Issue by adrelanos** [mikeperry-tor/vanguards#95]
This messages comes every second in journal.

> Oct 21 15:39:40 host vanguards[988]: WARNING[Sat Oct 21 15:39:40 2023]: Possible Tor bug, or possible attack if very frequent: Got 1 dropped cell on circ 17 (in state CONFLUX_LINKED None; old state CONFLUX_UNLINKED None)

* Debian 12 bookworm
* `tor` stable Debian package 0.4.8.7 from deb.torproject.org.
* `vanguards` package from from packages.debian.org.

**Comment by mikeperry-tor** [comment]
This should be fixed in https://gitlab.torproject.org/tpo/core/tor/-/issues/40878. It was backported to 0.4.8; will be in the next 0.4.8 release

**Comment by adrelanos** [comment]
This issue is still reproducible with the updated Tor version.

    dpkg -l | grep tor

> 0.4.8.9-1~d12.bookworm+1

From `deb.torproject.org`.

**Comment by adrelanos** [comment]
Correction: Actually not happening anymore every second.

This was fixed.

Thank you!
